CREATE TABLE student_enrollment (
    id uuid not null default gen_random_uuid (), 
   learner_reference_number character varying(50) null, 
   psa_birth_certificate_number character varying(100) null, 
   last_name character varying(100) not null, 
   first_name character varying(100) not null, 
   middle_name character varying(100) null, 
   extension_name character varying(20) null, 
   birthdate date not null, 
   age integer null, 
   sex character varying(10) null, 
   mother_tongue character varying(100) null, 
   email_address character varying(255) null, 
   phone_number character varying(20) null, 
   rfid_tag character varying(50) null, 
   school_year character varying(20) not null, 
   grade_level character varying(20) not null, 
   current_house_number character varying(50) null, 
   current_sitio_street character varying(200) null, 
   current_barangay character varying(100) null, 
   current_municipality_city character varying(100) null, 
   current_province character varying(100) null, 
   current_country character varying(100) null default 'Philippines'::character varying, 
   current_zip_code character varying(20) null, 
   permanent_house_number character varying(50) null, 
   permanent_street character varying(200) null, 
   permanent_barangay character varying(100) null, 
   permanent_municipality_city character varying(100) null, 
   permanent_province character varying(100) null, 
   permanent_country character varying(100) null default 'Philippines'::character varying, 
   permanent_zip_code character varying(20) null, 
   same_as_current_address boolean null default false, 
   place_of_birth_municipality_city character varying(100) null, 
   has_disability boolean null default false, 
   visual_impairment_blind boolean null default false, 
   visual_impairment_low_vision boolean null default false, 
   hearing_impairment boolean null default false, 
   learning_disability boolean null default false, 
   intellectual_disability boolean null default false, 
   autism_spectrum_disorder boolean null default false, 
   emotional_behavioral_disorder boolean null default false, 
   orthopedic_physical_handicap boolean null default false, 
   speech_language_disorder boolean null default false, 
   cerebral_palsy boolean null default false, 
   special_health_problem_chronic_disease boolean null default false, 
   special_health_problem_cancer boolean null default false, 
   multiple_disorder boolean null default false, 
   belongs_to_ip_community boolean null default false, 
   ip_community_name character varying(200) null, 
   is_4ps_beneficiary boolean null default false, 
   four_ps_household_id character varying(50) null, 
   father_last_name character varying(100) null, 
   father_first_name character varying(100) null, 
   father_middle_name character varying(100) null, 
   father_contact_number character varying(50) null, 
   mother_last_name character varying(100) null, 
   mother_first_name character varying(100) null, 
   mother_middle_name character varying(100) null, 
   mother_contact_number character varying(50) null, 
   guardian_last_name character varying(100) null, 
   guardian_first_name character varying(100) null, 
   guardian_middle_name character varying(100) null, 
   guardian_contact_number character varying(50) null, 
   has_lrn boolean null default false, 
   is_returning_learner boolean null default false, 
   last_grade_level_completed character varying(20) null, 
   last_school_year_completed character varying(20) null, 
   last_school_attended character varying(200) null, 
   last_school_id character varying(50) null, 
   semester character varying(10) null, 
   track character varying(100) null, 
   strand character varying(100) null, 
   prefers_modular_print boolean null default false, 
   prefers_modular_digital boolean null default false, 
   prefers_online boolean null default false, 
   prefers_educational_television boolean null default false, 
   prefers_radio_based_instruction boolean null default false, 
   prefers_blended boolean null default false, 
   prefers_homeschooling boolean null default false, 
   parent_guardian_signature_name character varying(200) null, 
   date_submitted date null default CURRENT_DATE, 
   created_at timestamp with time zone null default now(), 
   updated_at timestamp with time zone null default now()
);